// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: candle.proto

package my.demo.tradingview.message;

public final class CandleProto {
  private CandleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CandleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Candle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string time = 1;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <code>optional string time = 1;</code>
     * @return The time.
     */
    java.lang.String getTime();
    /**
     * <code>optional string time = 1;</code>
     * @return The bytes for time.
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>optional string open = 2;</code>
     * @return Whether the open field is set.
     */
    boolean hasOpen();
    /**
     * <code>optional string open = 2;</code>
     * @return The open.
     */
    java.lang.String getOpen();
    /**
     * <code>optional string open = 2;</code>
     * @return The bytes for open.
     */
    com.google.protobuf.ByteString
        getOpenBytes();

    /**
     * <code>optional string high = 3;</code>
     * @return Whether the high field is set.
     */
    boolean hasHigh();
    /**
     * <code>optional string high = 3;</code>
     * @return The high.
     */
    java.lang.String getHigh();
    /**
     * <code>optional string high = 3;</code>
     * @return The bytes for high.
     */
    com.google.protobuf.ByteString
        getHighBytes();

    /**
     * <code>optional string low = 4;</code>
     * @return Whether the low field is set.
     */
    boolean hasLow();
    /**
     * <code>optional string low = 4;</code>
     * @return The low.
     */
    java.lang.String getLow();
    /**
     * <code>optional string low = 4;</code>
     * @return The bytes for low.
     */
    com.google.protobuf.ByteString
        getLowBytes();

    /**
     * <code>optional string close = 5;</code>
     * @return Whether the close field is set.
     */
    boolean hasClose();
    /**
     * <code>optional string close = 5;</code>
     * @return The close.
     */
    java.lang.String getClose();
    /**
     * <code>optional string close = 5;</code>
     * @return The bytes for close.
     */
    com.google.protobuf.ByteString
        getCloseBytes();
  }
  /**
   * Protobuf type {@code demo.Candle}
   */
  public static final class Candle extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Candle)
      CandleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Candle.newBuilder() to construct.
    private Candle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Candle() {
      time_ = "";
      open_ = "";
      high_ = "";
      low_ = "";
      close_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Candle();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Candle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              time_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              open_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              high_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              low_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              close_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return my.demo.tradingview.message.CandleProto.internal_static_demo_Candle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return my.demo.tradingview.message.CandleProto.internal_static_demo_Candle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              my.demo.tradingview.message.CandleProto.Candle.class, my.demo.tradingview.message.CandleProto.Candle.Builder.class);
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object time_;
    /**
     * <code>optional string time = 1;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string time = 1;</code>
     * @return The bytes for time.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object open_;
    /**
     * <code>optional string open = 2;</code>
     * @return Whether the open field is set.
     */
    @java.lang.Override
    public boolean hasOpen() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string open = 2;</code>
     * @return The open.
     */
    @java.lang.Override
    public java.lang.String getOpen() {
      java.lang.Object ref = open_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          open_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string open = 2;</code>
     * @return The bytes for open.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOpenBytes() {
      java.lang.Object ref = open_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        open_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HIGH_FIELD_NUMBER = 3;
    private volatile java.lang.Object high_;
    /**
     * <code>optional string high = 3;</code>
     * @return Whether the high field is set.
     */
    @java.lang.Override
    public boolean hasHigh() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string high = 3;</code>
     * @return The high.
     */
    @java.lang.Override
    public java.lang.String getHigh() {
      java.lang.Object ref = high_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          high_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string high = 3;</code>
     * @return The bytes for high.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHighBytes() {
      java.lang.Object ref = high_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        high_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOW_FIELD_NUMBER = 4;
    private volatile java.lang.Object low_;
    /**
     * <code>optional string low = 4;</code>
     * @return Whether the low field is set.
     */
    @java.lang.Override
    public boolean hasLow() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string low = 4;</code>
     * @return The low.
     */
    @java.lang.Override
    public java.lang.String getLow() {
      java.lang.Object ref = low_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          low_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string low = 4;</code>
     * @return The bytes for low.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLowBytes() {
      java.lang.Object ref = low_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        low_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLOSE_FIELD_NUMBER = 5;
    private volatile java.lang.Object close_;
    /**
     * <code>optional string close = 5;</code>
     * @return Whether the close field is set.
     */
    @java.lang.Override
    public boolean hasClose() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string close = 5;</code>
     * @return The close.
     */
    @java.lang.Override
    public java.lang.String getClose() {
      java.lang.Object ref = close_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          close_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string close = 5;</code>
     * @return The bytes for close.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCloseBytes() {
      java.lang.Object ref = close_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        close_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, time_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, open_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, high_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, low_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, close_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, time_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, open_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, high_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, low_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, close_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof my.demo.tradingview.message.CandleProto.Candle)) {
        return super.equals(obj);
      }
      my.demo.tradingview.message.CandleProto.Candle other = (my.demo.tradingview.message.CandleProto.Candle) obj;

      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (!getTime()
            .equals(other.getTime())) return false;
      }
      if (hasOpen() != other.hasOpen()) return false;
      if (hasOpen()) {
        if (!getOpen()
            .equals(other.getOpen())) return false;
      }
      if (hasHigh() != other.hasHigh()) return false;
      if (hasHigh()) {
        if (!getHigh()
            .equals(other.getHigh())) return false;
      }
      if (hasLow() != other.hasLow()) return false;
      if (hasLow()) {
        if (!getLow()
            .equals(other.getLow())) return false;
      }
      if (hasClose() != other.hasClose()) return false;
      if (hasClose()) {
        if (!getClose()
            .equals(other.getClose())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      if (hasOpen()) {
        hash = (37 * hash) + OPEN_FIELD_NUMBER;
        hash = (53 * hash) + getOpen().hashCode();
      }
      if (hasHigh()) {
        hash = (37 * hash) + HIGH_FIELD_NUMBER;
        hash = (53 * hash) + getHigh().hashCode();
      }
      if (hasLow()) {
        hash = (37 * hash) + LOW_FIELD_NUMBER;
        hash = (53 * hash) + getLow().hashCode();
      }
      if (hasClose()) {
        hash = (37 * hash) + CLOSE_FIELD_NUMBER;
        hash = (53 * hash) + getClose().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static my.demo.tradingview.message.CandleProto.Candle parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static my.demo.tradingview.message.CandleProto.Candle parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static my.demo.tradingview.message.CandleProto.Candle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static my.demo.tradingview.message.CandleProto.Candle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static my.demo.tradingview.message.CandleProto.Candle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static my.demo.tradingview.message.CandleProto.Candle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static my.demo.tradingview.message.CandleProto.Candle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static my.demo.tradingview.message.CandleProto.Candle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static my.demo.tradingview.message.CandleProto.Candle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static my.demo.tradingview.message.CandleProto.Candle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static my.demo.tradingview.message.CandleProto.Candle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static my.demo.tradingview.message.CandleProto.Candle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(my.demo.tradingview.message.CandleProto.Candle prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Candle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Candle)
        my.demo.tradingview.message.CandleProto.CandleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return my.demo.tradingview.message.CandleProto.internal_static_demo_Candle_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return my.demo.tradingview.message.CandleProto.internal_static_demo_Candle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                my.demo.tradingview.message.CandleProto.Candle.class, my.demo.tradingview.message.CandleProto.Candle.Builder.class);
      }

      // Construct using my.demo.tradingview.message.CandleProto.Candle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        open_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        high_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        low_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        close_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return my.demo.tradingview.message.CandleProto.internal_static_demo_Candle_descriptor;
      }

      @java.lang.Override
      public my.demo.tradingview.message.CandleProto.Candle getDefaultInstanceForType() {
        return my.demo.tradingview.message.CandleProto.Candle.getDefaultInstance();
      }

      @java.lang.Override
      public my.demo.tradingview.message.CandleProto.Candle build() {
        my.demo.tradingview.message.CandleProto.Candle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public my.demo.tradingview.message.CandleProto.Candle buildPartial() {
        my.demo.tradingview.message.CandleProto.Candle result = new my.demo.tradingview.message.CandleProto.Candle(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.open_ = open_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.high_ = high_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.low_ = low_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.close_ = close_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof my.demo.tradingview.message.CandleProto.Candle) {
          return mergeFrom((my.demo.tradingview.message.CandleProto.Candle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(my.demo.tradingview.message.CandleProto.Candle other) {
        if (other == my.demo.tradingview.message.CandleProto.Candle.getDefaultInstance()) return this;
        if (other.hasTime()) {
          bitField0_ |= 0x00000001;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasOpen()) {
          bitField0_ |= 0x00000002;
          open_ = other.open_;
          onChanged();
        }
        if (other.hasHigh()) {
          bitField0_ |= 0x00000004;
          high_ = other.high_;
          onChanged();
        }
        if (other.hasLow()) {
          bitField0_ |= 0x00000008;
          low_ = other.low_;
          onChanged();
        }
        if (other.hasClose()) {
          bitField0_ |= 0x00000010;
          close_ = other.close_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        my.demo.tradingview.message.CandleProto.Candle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (my.demo.tradingview.message.CandleProto.Candle) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object time_ = "";
      /**
       * <code>optional string time = 1;</code>
       * @return Whether the time field is set.
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string time = 1;</code>
       * @return The time.
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            time_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string time = 1;</code>
       * @return The bytes for time.
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string time = 1;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string time = 1;</code>
       * @param value The bytes for time to set.
       * @return This builder for chaining.
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object open_ = "";
      /**
       * <code>optional string open = 2;</code>
       * @return Whether the open field is set.
       */
      public boolean hasOpen() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string open = 2;</code>
       * @return The open.
       */
      public java.lang.String getOpen() {
        java.lang.Object ref = open_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            open_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string open = 2;</code>
       * @return The bytes for open.
       */
      public com.google.protobuf.ByteString
          getOpenBytes() {
        java.lang.Object ref = open_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          open_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string open = 2;</code>
       * @param value The open to set.
       * @return This builder for chaining.
       */
      public Builder setOpen(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        open_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string open = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpen() {
        bitField0_ = (bitField0_ & ~0x00000002);
        open_ = getDefaultInstance().getOpen();
        onChanged();
        return this;
      }
      /**
       * <code>optional string open = 2;</code>
       * @param value The bytes for open to set.
       * @return This builder for chaining.
       */
      public Builder setOpenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        open_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object high_ = "";
      /**
       * <code>optional string high = 3;</code>
       * @return Whether the high field is set.
       */
      public boolean hasHigh() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string high = 3;</code>
       * @return The high.
       */
      public java.lang.String getHigh() {
        java.lang.Object ref = high_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            high_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string high = 3;</code>
       * @return The bytes for high.
       */
      public com.google.protobuf.ByteString
          getHighBytes() {
        java.lang.Object ref = high_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          high_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string high = 3;</code>
       * @param value The high to set.
       * @return This builder for chaining.
       */
      public Builder setHigh(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        high_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string high = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHigh() {
        bitField0_ = (bitField0_ & ~0x00000004);
        high_ = getDefaultInstance().getHigh();
        onChanged();
        return this;
      }
      /**
       * <code>optional string high = 3;</code>
       * @param value The bytes for high to set.
       * @return This builder for chaining.
       */
      public Builder setHighBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        high_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object low_ = "";
      /**
       * <code>optional string low = 4;</code>
       * @return Whether the low field is set.
       */
      public boolean hasLow() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string low = 4;</code>
       * @return The low.
       */
      public java.lang.String getLow() {
        java.lang.Object ref = low_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            low_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string low = 4;</code>
       * @return The bytes for low.
       */
      public com.google.protobuf.ByteString
          getLowBytes() {
        java.lang.Object ref = low_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          low_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string low = 4;</code>
       * @param value The low to set.
       * @return This builder for chaining.
       */
      public Builder setLow(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        low_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string low = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLow() {
        bitField0_ = (bitField0_ & ~0x00000008);
        low_ = getDefaultInstance().getLow();
        onChanged();
        return this;
      }
      /**
       * <code>optional string low = 4;</code>
       * @param value The bytes for low to set.
       * @return This builder for chaining.
       */
      public Builder setLowBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        low_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object close_ = "";
      /**
       * <code>optional string close = 5;</code>
       * @return Whether the close field is set.
       */
      public boolean hasClose() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string close = 5;</code>
       * @return The close.
       */
      public java.lang.String getClose() {
        java.lang.Object ref = close_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            close_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string close = 5;</code>
       * @return The bytes for close.
       */
      public com.google.protobuf.ByteString
          getCloseBytes() {
        java.lang.Object ref = close_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          close_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string close = 5;</code>
       * @param value The close to set.
       * @return This builder for chaining.
       */
      public Builder setClose(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        close_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string close = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearClose() {
        bitField0_ = (bitField0_ & ~0x00000010);
        close_ = getDefaultInstance().getClose();
        onChanged();
        return this;
      }
      /**
       * <code>optional string close = 5;</code>
       * @param value The bytes for close to set.
       * @return This builder for chaining.
       */
      public Builder setCloseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        close_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.Candle)
    }

    // @@protoc_insertion_point(class_scope:demo.Candle)
    private static final my.demo.tradingview.message.CandleProto.Candle DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new my.demo.tradingview.message.CandleProto.Candle();
    }

    public static my.demo.tradingview.message.CandleProto.Candle getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Candle>
        PARSER = new com.google.protobuf.AbstractParser<Candle>() {
      @java.lang.Override
      public Candle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Candle(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Candle> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Candle> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public my.demo.tradingview.message.CandleProto.Candle getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Candle_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Candle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014candle.proto\022\004demo\"N\n\006Candle\022\014\n\004time\030\001" +
      " \001(\t\022\014\n\004open\030\002 \001(\t\022\014\n\004high\030\003 \001(\t\022\013\n\003low\030" +
      "\004 \001(\t\022\r\n\005close\030\005 \001(\tB*\n\033my.demo.tradingv" +
      "iew.messageB\013CandleProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_demo_Candle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_Candle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Candle_descriptor,
        new java.lang.String[] { "Time", "Open", "High", "Low", "Close", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
